name: Upload Schema Artifact

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release tag to upload the schema to'
        required: true
        type: string

permissions:
  contents: write

jobs:
  schema:
    name: Generate and Upload WPGraphQL Schema Artifact
    uses: AxeWP/plugin-infra/.github/workflows/reusable-upload-schema-artifact.yml@main
    with:
      php-version: '8.2'
      plugin-slug: 'wp-graphql-plugin-name'
      release-tag: ${{ inputs.release-tag || '' }}
