name: Code Quality - Boilerplate

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          working-directory: ./wp-graphql-plugin-name
          composer-options: "--no-progress"

      - name: Configure local dependency
        run: |
          composer config repositories.local '{"type": "path", "url": "../", "options": {"symlink": false}}'
          composer require axepress/wp-graphql-plugin-boilerplate:@dev
        working-directory: ./wp-graphql-plugin-name

      - name: Run PHPStan
        working-directory: ./wp-graphql-plugin-name
        run: composer run-script phpstan -- -vvv
